[jupiter.mysql.master]
   connMaxLifetime = "300s"
   debug = true
   dsn = "root:12345678@tcp(192.168.3.39:3306)/go-ops?charset=utf8&parseTime=True&loc=Local&readTimeout=1s&timeout=1s&writeTimeout=3s"
   level = "panic"
   maxIdleConns = 50
   maxOpenConns = 100
